name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  sqflite: ^2.0.3+1
  expansion_tile_card: ^2.0.0
  animated_splash_screen: ^1.3.0
  flutter_svg: ^1.1.4
  transitions_page: ^1.0.0
  path: ^1.8.1

flutter_icons:
  android: true
  iOS: true
  image_path: "Assets/Logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/
